sudo: false
language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
 global:
 - ANDROID_API=30
 - ANDROID_BUILD_TOOLS=29.0.2
android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS
  - addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
  - '.+'
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
install:
- "./gradlew dependencies"
script:
- "./gradlew ktlintCheck"
- "./gradlew check"
before_deploy:
- cat "$TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"
- cat "$TRAVIS_BUILD_DIR/app/build/reports/pmd/duplicates.xml"
- cat "$TRAVIS_BUILD_DIR/app/build/reports/detekt/detekt-checkstyle.xml"
- cat "$TRAVIS_BUILD_DIR/app/build/reports/findbugs/findBugsDebug.xml"