package de.tum.`in`.tumcampusapp.utils

object ConfigConst {
    const val CAMPUS = "CAMPUS"

    const val API = "API"
    const val API_BASE_URL = "API_BASE_URL"

    const val AUTH_METHOD = "AUTH_METHOD"

    const val OAUTH_CONSUMER_KEY = "OAUTH_CONSUMER_KEY"
    const val OAUTH_CONSUMER_SECRET = "OAUTH_CONSUMER_SECRET"
    const val OAUTH_REQUEST_TOKEN_URL = "OAUTH_REQUEST_TOKEN_URL"
    const val OAUTH_ACCESS_TOKEN_URL = "OAUTH_ACCESS_TOKEN_URL"
    const val OAUTH_AUTHORIZE_URL = "OAUTH_AUTHORIZE_URL"
    const val OAUTH_SIGNATURE_METHOD = "OAUTH_SIGNATURE_METHOD"

    const val CALENDAR_ENABLED = "CALENDAR_ENABLED"
    const val GRADES_ENABLED = "GRADES_ENABLED"
    const val LECTURES_ENABLED = "LECTURES_ENABLED"
    const val PERSON_ENABLED = "PERSON_ENABLED"
    const val ROOMFINDER_ENABLED = "ROOMFINDER_ENABLED"
    const val TUITIONFEES_ENABLED = "TUITIONFEES_ENABLED"
    const val CAFETERIA_ENABLED = "CAFETERIA_ENABLED"
    const val CHAT_ENABLED = "CHAT_ENABLED"
    const val EDUROAM_ENABLED = "EDUROAM_ENABLED"
    const val NEWS_ENABLED = "NEWS_ENABLED"
    const val OPENINGHOUR_ENABLED = "OPENINGHOUR_ENABLED"
    const val TRANSPORTATION_ENABLED = "TRANSPORTATION_ENABLED"
    const val STUDYROOM_ENABLED = "STUDYROOM_ENABLED"

    const val CALENDAR_EDITABLE = "CALENDAR_EDITABLE"

    const val EDUROAM_DOMAINS = "EDUROAM_DOMAINS"
    const val EDUROAM_RADIUS_SERVER = "EDUROAM_RADIUS_SERVER"
    const val EDUROAM_ANONYMOUS_IDENTITIES = "EDUROAM_ANONYMOUS_IDENTITIES"

    const val TUITIONFEES_TUITION = "TUITIONFEES_TUITION"
    const val TUITIONFEES_FROM_API = "TUITIONFEES_FROM_API"
    const val TUITIONFEES_LINK = "TUITIONFEES_LINK"

    const val CHAT_ROOM_CREATEABLE = "CHAT_ROOM_CREATEABLE"
    const val CHAT_ROOM_JOINABLE = "CHAT_ROOM_JOINABLE"
    const val CHAT_ROOM_LEAVEABLE = "CHAT_ROOM_LEAVEABLE"
    const val CHAT_ROOM_MEMBER_ADDABLE = "CHAT_ROOM_MEMBER_ADDABLE"

    const val TRANSPORTATION_API = "TRANSPORTATION_API"

    const val CAFETERIA_API = "CAFETERIA_API"
    const val CAFETERIA_INGREDIENTS_TEXT = "CAFETERIA_INGREDIENTS_TEXT"
}