name: CI
on:
  pull_request:
    branches: master
jobs:
  test-build:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Check Dependencies
          run: ./gradlew dependencies
        - name: Lint
          run: ./gradlew klintCheck
        - name: Test
          run: ./gradlew test
